[src]
respect-ignore-files = true
include = ["**/*.py"]
exclude = [
    "demos/demo_assembly.py",
    "demos/demo_inhand.py",
    "demos/demo_keyboard_teleop.py",
    "demos/demo_teleop.py",
    "experiments/evaluate_stability.py",
    "experiments/static_analysis.py",
]
