"""Generate ty config for Isaac Sim extension imports."""

import argparse
import importlib.util
import os
import shutil
import sys
from pathlib import Path
from typing import Iterable

import toml

GENERATOR_NAME = "bricksim.cli.type_configs"
ISAACLAB_SOURCE_PACKAGES = (
    "isaaclab",
    "isaaclab_assets",
    "isaaclab_mimic",
    "isaaclab_rl",
    "isaaclab_tasks",
)
PACKAGE_MARKER = f"# Generated by {GENERATOR_NAME} for static analysis only.\n"
ISAACSIM_PACKAGE_MARKER = (
    f"# Generated by {GENERATOR_NAME} for static analysis only.\n"
    "from typing import NoReturn\n"
    "\n"
    "from .simulation_app import AppFramework, SimulationApp\n"
    "\n"
    "def main() -> NoReturn: ...\n"
)


def _resolve_ty_base_config_path(root: Path, config_path: Path | None) -> Path:
    if config_path is None:
        return root / "ty.base.toml"
    if config_path.is_absolute():
        return config_path.resolve()
    return (root / config_path).resolve()


def _iter_subdirs(base: Path) -> Iterable[Path]:
    if not base.is_dir():
        return
    for entry in base.iterdir():
        if entry.is_dir():
            yield entry


def _resolve_isaaclab_source_root() -> Path | None:
    spec = importlib.util.find_spec("isaaclab")
    if spec is None:
        return None
    if spec.origin is None:
        raise RuntimeError("Unable to resolve Isaac Lab module origin")

    module_dir = Path(os.path.realpath(spec.origin)).parent

    nested_source_root = module_dir / "source"
    if (nested_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return nested_source_root.resolve()

    editable_source_root = module_dir.parent.parent
    if (editable_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return editable_source_root.resolve()

    raise RuntimeError(f"Unable to resolve Isaac Lab source root from {module_dir}")


def collect_isaaclab_source_roots() -> list[Path]:
    """Collect Isaac Lab source roots from the active Python environment.

    Returns:
        Isaac Lab package roots that should be import search paths.
    """
    isaaclab_source_root = _resolve_isaaclab_source_root()
    if isaaclab_source_root is None:
        return []
    return [
        (isaaclab_source_root / package_name).resolve()
        for package_name in ISAACLAB_SOURCE_PACKAGES
    ]


def _iter_extension_python_modules(ext_dir: Path) -> Iterable[tuple[Path, str]]:
    config_path = ext_dir / "config" / "extension.toml"
    if not config_path.is_file():
        return []
    try:
        config = toml.load(config_path)
    except toml.TomlDecodeError:
        return []
    python_modules = config.get("python", {}).get("module", [])
    if isinstance(python_modules, dict):
        python_modules = [python_modules]
    module_entries = [item for item in python_modules if isinstance(item, dict)]

    seen: set[tuple[str, str]] = set()
    for entry in module_entries:
        module_root = (ext_dir / entry.get("path", ".")).resolve()
        module_name = entry.get("name", "")
        if not module_name or module_name.endswith(".tests"):
            continue
        key = (str(module_root), module_name)
        if key in seen:
            continue
        seen.add(key)
        yield module_root, module_name


def _iter_parent_packages(module_name: str) -> Iterable[tuple[str, ...]]:
    parts = module_name.split(".")
    for depth in range(1, len(parts)):
        yield tuple(parts[:depth])


def _resolve_extension_module_path(module_root: Path, module_name: str) -> Path | None:
    parts = module_name.split(".")
    package_path = module_root.joinpath(*parts)
    if package_path.is_dir():
        return package_path

    module_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.py")
    if module_path.is_file():
        return module_path

    stub_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.pyi")
    if stub_path.is_file():
        return stub_path

    return None


def _ensure_overlay_package(
    overlay_dir: Path,
    package_parts: tuple[str, ...],
) -> Path:
    package_dir = overlay_dir.joinpath(*package_parts)
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        content = (
            ISAACSIM_PACKAGE_MARKER
            if package_parts == ("isaacsim",)
            else PACKAGE_MARKER
        )
        init_path.write_text(content, encoding="utf-8")
    return package_dir


def _symlink_if_absent(path: Path, target: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.symlink_to(target)


def _mirror_extension_module(
    module_root: Path,
    module_name: str,
    all_module_names: set[str],
    *,
    overlay_dir: Path,
) -> None:
    module_source = _resolve_extension_module_path(module_root, module_name)
    if module_source is None:
        return

    parts = module_name.split(".")
    for package_parts in _iter_parent_packages(module_name):
        _ensure_overlay_package(overlay_dir, package_parts)

    if module_source.is_file():
        overlay_file = overlay_dir.joinpath(*parts[:-1], module_source.name)
        _symlink_if_absent(overlay_file, module_source)
        return

    target_dir = overlay_dir.joinpath(*parts)
    target_dir.mkdir(parents=True, exist_ok=True)
    for entry in module_source.iterdir():
        if entry.name == "__pycache__":
            continue
        if entry.is_dir():
            child_module_name = f"{module_name}.{entry.name}"
            if any(
                candidate == child_module_name
                or candidate.startswith(f"{child_module_name}.")
                for candidate in all_module_names
            ):
                continue
        elif entry.suffix == ".py" and entry.stem != "__init__":
            child_module_name = f"{module_name}.{entry.stem}"
        else:
            child_module_name = ""
        if child_module_name and child_module_name in all_module_names:
            continue
        _symlink_if_absent(target_dir / entry.name, entry)

    init_path = target_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(PACKAGE_MARKER, encoding="utf-8")


def collect_isaacsim_extension_paths() -> list[Path]:
    """Collect Isaac Sim extension roots from the active Python environment.

    Returns:
        Deduplicated extension directories that may contain Python modules.
    """
    import isaacsim

    isaacsim_path = Path(os.path.realpath(isaacsim.__file__)).parent
    kit_path = isaacsim_path / "kit"
    paths: list[Path] = []

    kernel_py = kit_path / "kernel" / "py"
    if kernel_py.is_dir():
        paths.append(kernel_py)

    for folder in ("exts", "extscore"):
        paths.extend(_iter_subdirs(kit_path / folder))
    for folder in ("exts", "extscache", "extsDeprecated", "extsUser"):
        paths.extend(_iter_subdirs(isaacsim_path / folder))
    paths.extend(_iter_user_kit_extensions())
    return _dedupe_resolved_paths(paths)


def _iter_user_kit_extensions() -> Iterable[Path]:
    ov_base = Path.home() / ".local" / "share" / "ov" / "data" / "Kit"
    if not ov_base.is_dir():
        return
    for kit_dir in ov_base.iterdir():
        if not kit_dir.is_dir():
            continue
        for exts_root in kit_dir.rglob("exts"):
            if not exts_root.is_dir():
                continue
            for layer_dir in _iter_subdirs(exts_root):
                yield from _iter_subdirs(layer_dir)


def _dedupe_resolved_paths(paths: Iterable[Path]) -> list[Path]:
    seen: set[str] = set()
    result: list[Path] = []
    for path in paths:
        normalized = path.resolve()
        normalized_str = str(normalized)
        if normalized_str in seen:
            continue
        seen.add(normalized_str)
        result.append(normalized)
    return result


def _relative_or_absolute(path: Path, root: Path) -> str:
    try:
        return f"./{path.relative_to(root).as_posix()}"
    except ValueError:
        return path.as_posix()


def write_ty_overlay(
    root: Path, extension_paths: Iterable[Path], overlay_dir: Path
) -> str:
    """Write the ty overlay that mirrors selected extension modules.

    Returns:
        Overlay path rendered relative to the project root when possible.
    """
    extension_modules: list[tuple[Path, str]] = []
    module_names: set[str] = set()
    for ext_path in extension_paths:
        for module_root, module_name in _iter_extension_python_modules(ext_path):
            if module_name != "isaacsim" and not module_name.startswith("isaacsim."):
                continue
            module_names.add(module_name)
            extension_modules.append((module_root, module_name))

    if overlay_dir.exists():
        shutil.rmtree(overlay_dir)
    overlay_dir.mkdir(parents=True)

    for module_root, module_name in extension_modules:
        _mirror_extension_module(
            module_root, module_name, module_names, overlay_dir=overlay_dir
        )

    return _relative_or_absolute(overlay_dir, root)


def render_ty_config(
    *,
    base_config: dict[str, object],
    ty_extra_paths: list[str],
) -> str:
    """Render the generated ty configuration file.

    Returns:
        TOML text for ``ty.toml``.
    """
    header = (
        f"# Generated by {GENERATOR_NAME}.\n"
        "# Edit ty.base.toml for stable project settings.\n"
    )
    config = base_config.copy()
    environment_config = config.get("environment")
    environment_table: dict[str, object] = {}
    if isinstance(environment_config, dict):
        for key, value in environment_config.items():
            if not isinstance(key, str):
                raise RuntimeError(
                    "[environment] keys in ty base config must be strings."
                )
            environment_table[key] = value
    elif environment_config is not None:
        raise RuntimeError("[environment] in ty base config must be a table.")

    base_extra_paths = environment_table.get("extra-paths", [])
    if isinstance(base_extra_paths, str) or not isinstance(base_extra_paths, list):
        raise RuntimeError(
            "[environment].extra-paths in ty base config must be a list."
        )
    environment_table["extra-paths"] = [*base_extra_paths, *ty_extra_paths]
    config["environment"] = environment_table
    encoder = toml.TomlArraySeparatorEncoder(separator=",\n")
    body = toml.dumps(config, encoder=encoder)
    return f"{header}\n{body}"


def read_ty_base_config(config_path: Path) -> dict[str, object]:
    """Read stable ty configuration copied into the generated config.

    Returns:
        Parsed ty base configuration, or an empty config when absent.
    """
    if not config_path.is_file():
        return {}
    return toml.load(config_path)


def generate(
    *,
    root: Path,
    config_path: Path,
    overlay_dir: Path,
    base_config_path: Path,
) -> None:
    """Generate ty overlay and config."""
    isaaclab_source_roots = collect_isaaclab_source_roots()
    if not isaaclab_source_roots:
        print("IsaacLab not found; skipping IsaacLab type paths.")
    isaacsim_extension_paths = collect_isaacsim_extension_paths()

    ty_overlay_path = write_ty_overlay(root, isaacsim_extension_paths, overlay_dir)

    ty_extra_paths = [
        *(_relative_or_absolute(path, root) for path in isaaclab_source_roots),
        *(_relative_or_absolute(path, root) for path in isaacsim_extension_paths),
    ]
    ty_extra_paths.insert(0, ty_overlay_path)
    ty_base_config = read_ty_base_config(base_config_path)
    ty_config_text = render_ty_config(
        base_config=ty_base_config,
        ty_extra_paths=ty_extra_paths,
    )
    config_path.write_text(ty_config_text, encoding="utf-8")


def _print_generation_targets(
    *, config_path: Path, overlay_dir: Path, base_config_path: Path
) -> None:
    base_config_message = base_config_path if base_config_path.is_file() else "none"
    print(f"Using ty base config: {base_config_message}")
    print("The following paths will be overwritten:")
    print(f"  ty config: {config_path}")
    print(f"  ty overlay: {overlay_dir}")


def _confirm_overwrite(config_path: Path, overlay_dir: Path) -> bool:
    if not sys.stdin.isatty():
        raise RuntimeError(
            "Refusing to write without confirmation on a non-interactive stdin. "
            "Pass -y to apply non-interactively."
        )
    response = input("Apply these changes? [y/N]: ").strip().lower()
    return response in {"y", "yes"}


def main() -> int:
    """Run the type-config generator CLI.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(
        description="Collect Isaac Sim / Omniverse python paths for ty."
    )
    parser.add_argument(
        "-y",
        action="store_true",
        help="Apply changes without interactive confirmation.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("."),
        help=(
            "Target project root where configuration files should be written "
            "(default: current directory)."
        ),
    )
    parser.add_argument(
        "--ty-base-config",
        type=Path,
        default=None,
        help=(
            "Base ty config copied into generated ty.toml "
            "(default: ty.base.toml under --root)."
        ),
    )
    args = parser.parse_args()

    root = args.root.resolve()
    config_path = root / "ty.toml"
    overlay_dir = root / ".ty" / "extension-packages"
    base_config_path = _resolve_ty_base_config_path(root, args.ty_base_config)

    _print_generation_targets(
        config_path=config_path,
        overlay_dir=overlay_dir,
        base_config_path=base_config_path,
    )
    if not args.y and not _confirm_overwrite(config_path, overlay_dir):
        print("Aborted.")
        return 1

    generate(
        root=root,
        config_path=config_path,
        overlay_dir=overlay_dir,
        base_config_path=base_config_path,
    )
    print(f"Wrote {config_path}")
    print(f"Wrote {overlay_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
